version: '3'

services:
  app:
    image: node:18
    init: true
    restart: always
    environment:
      # MQTT ブローカー待ち受けポート
      VITE_MQTT_URL: ws://host.docker.internal:9090/mqtt
      VITE_MQTT_USER_NAME: read
      VITE_MQTT_PASSWORD: password
    command: ["sleep", "infinity"]
    ports:
      # フロントエンドの devserver 待ち受けポート
      - 0.0.0.0:5173:5173
    volumes:
      # プロジェクトルート
      - "./:/work"
      # node 関連
      - "node_modules:/work/frontend/node_modules"
    working_dir: /work
  emqx:
    image: emqx/emqx
    init: true
    restart: always
    ports:
      # MQTT over WebSocket の待ち受けポート
      - 0.0.0.0:9090:8083
      # ダッシュボードの待ち受けポート
      - 0.0.0.0:18083:18083
    volumes:
      # emqx コア設定ファイル
      - ./.devcontainer/config/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      # 認可設定ファイル
      - ./.devcontainer/config/emqx/etc/acl.conf:/opt/emqx/etc/acl.conf
      # 永続化用
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    environment:
      # ユーザー認証用モジュールを有効化
      EMQX_LOADED_PLUGINS: emqx_auth_username
    healthcheck:
      test: /opt/emqx/bin/emqx_ctl status
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 5s
  emqx-init:
    image: alpine/curl
    init: true
    restart: "no"
    depends_on:
      emqx:
        condition: service_healthy
    volumes:
      # 初期化スクリプト
      - "./.devcontainer/script/emqx-init/init.sh:/init.sh"
    command:
      - /init.sh

volumes:
  node_modules:
    driver: local
  emqx_data:
    driver: local
  emqx_log:
    driver: local

